import type { BrainDocument, Thought } from './types'

const C = {
  teal: '#2ec4b6',
  amber: '#e0a106',
  green: '#3dcf70',
  violet: '#a78bfa',
  rose: '#f472b6',
  sky: '#38bdf8',
  slate: '#94a3b8',
}

function t(id: string, name: string, color: string, notes: string, extra: Partial<Thought> = {}): Thought {
  return { id, name, color, notes, tags: extra.tags ?? [], attachments: extra.attachments ?? [], label: extra.label, icon: extra.icon }
}

export const SEED: BrainDocument = {
  schemaVersion: 3,
  title: 'Dream Unity',
  homeId: 'home',
  activeId: 'home',
  pins: ['home', 'unity-core', 'creative-freedom', 'maker', 'world'],
  history: ['home'],
  updatedAt: '2026-09-01T00:00:00.000Z',
  thoughts: [
    t('home', 'Dream Unity', C.violet, 'Home thought. Dream worlds are compressed, synthesised and realised in the physical before returning, transformed, to their originating ether.', { label: 'Home', tags: ['home'] }),
    t('maker', 'Maker', C.teal, 'Imagination, consciousness, identity, agency and primality. The one who aims and the hand that stays in the work.', { tags: ['portal'] }),
    t('machine', 'Machine', C.amber, 'Relation, constraint, compression, synthesis and generative process. The model that can be run.', { tags: ['portal'] }),
    t('world', 'World', C.green, 'Strategy, embodiment, artifacts, environments and lived consequence. The weather the theory must survive.', { tags: ['portal'] }),
    t('unity', 'Unity', C.violet, 'Principles and models that span Maker, Machine and World without flattening their difference.', { tags: ['portal'] }),
    t('unity-core', 'Unity Core', C.violet, 'The coherent convergence of maker, machine and world.\nThe generative ground and telos of the whole theory.\n\nUnity is not a fourth object placed beside the others. It is the field in which the three stop contradicting one another long enough to generate a world worth inhabiting.', { label: 'Core', tags: ['core', 'principle'] }),
    t('intention', 'Intention', C.teal, 'Directed attention and generative purpose. Intention is not a wish. It is the directed cut that makes a field of possibility usable.', { tags: ['facet'] }),
    t('craft', 'Craft', C.teal, 'Skill, method and the shaping of possibility. Craft is how intention survives contact with resistance.', { tags: ['facet'] }),
    t('insight', 'Insight', C.teal, 'Pattern recognition and the spark of understanding. Capture the spark in a sentence before explaining it.', { tags: ['facet'] }),
    t('creative-freedom', 'Creative Freedom', C.rose, 'Freedom is not the absence of constraint, but the presence of aligned possibility. It arises when the maker, the world and the work cohere into a generative field.\n\nConstraints become sculptural. Choices become expressive. Still provisional.', { label: 'Lens', tags: ['principle', 'freedom'] }),
    t('model', 'Model', C.amber, 'Abstract structure and predictive representation. A model is a compressed world that can be run. Its virtue is usable fidelity, not completeness.', { tags: ['form'] }),
    t('engine', 'Engine', C.amber, 'Computation, process and execution. The engine turns a model into motion.', { tags: ['form'] }),
    t('tool', 'Tool', C.amber, 'Instrument and interface for application. A tool is a model that has learned a hand.', { tags: ['form'] }),
    t('context', 'Context', C.green, 'Environment, culture and lived condition. No claim is free of the room it is spoken in.', { tags: ['field'] }),
    t('system', 'System', C.green, 'Networks, ecologies and interrelated dynamics. A system is a field with memory.', { tags: ['field'] }),
    t('impact', 'Impact', C.green, 'Consequence, value and legacy. Impact is theory after it has touched a life.', { tags: ['field'] }),
    t('coherence', 'Coherence', C.violet, 'Internal alignment and non-contradiction. The refusal of the theory to lie to itself.', { tags: ['principle'] }),
    t('resonance', 'Resonance', C.violet, 'Deep agreement across forms and fields. Independent forms humming in the same key without being told to.', { tags: ['principle'] }),
    t('transcendence', 'Transcendence', C.sky, 'Beyond parts. The whole as generative one.', { tags: ['principle'] }),
    t('expressive-constraints', 'Expressive Constraints', C.rose, 'Tension as structure. The resistance that makes form possible.', { tags: ['tension'] }),
    t('mirror', 'Mirror', C.sky, 'Direct experience versus representation. Name the primal value, the inversion risk, the falsifier and the restoring action.', { tags: ['practice'] }),
    t('realisation', 'Realisation Lab', C.green, 'Convert a form into a practice: proposed act, expected observation, observed outcome, later reflection.', { tags: ['practice'] }),
  ],
  links: [
    { id: 'l1', kind: 'child', from: 'home', to: 'maker' },
    { id: 'l2', kind: 'child', from: 'home', to: 'machine' },
    { id: 'l3', kind: 'child', from: 'home', to: 'world' },
    { id: 'l4', kind: 'child', from: 'home', to: 'unity' },
    { id: 'l5', kind: 'child', from: 'maker', to: 'intention' },
    { id: 'l6', kind: 'child', from: 'maker', to: 'craft' },
    { id: 'l7', kind: 'child', from: 'maker', to: 'insight' },
    { id: 'l8', kind: 'child', from: 'maker', to: 'creative-freedom' },
    { id: 'l9', kind: 'child', from: 'machine', to: 'model' },
    { id: 'l10', kind: 'child', from: 'machine', to: 'engine' },
    { id: 'l11', kind: 'child', from: 'machine', to: 'tool' },
    { id: 'l12', kind: 'child', from: 'world', to: 'context' },
    { id: 'l13', kind: 'child', from: 'world', to: 'system' },
    { id: 'l14', kind: 'child', from: 'world', to: 'impact' },
    { id: 'l15', kind: 'child', from: 'unity', to: 'unity-core' },
    { id: 'l16', kind: 'child', from: 'unity', to: 'coherence' },
    { id: 'l17', kind: 'child', from: 'unity', to: 'resonance' },
    { id: 'l18', kind: 'child', from: 'unity', to: 'transcendence' },
    { id: 'l19', kind: 'child', from: 'creative-freedom', to: 'expressive-constraints' },
    { id: 'l20', kind: 'child', from: 'home', to: 'mirror' },
    { id: 'l21', kind: 'child', from: 'home', to: 'realisation' },
    { id: 'j1', kind: 'jump', from: 'unity-core', to: 'creative-freedom' },
    { id: 'j2', kind: 'jump', from: 'unity-core', to: 'maker' },
    { id: 'j3', kind: 'jump', from: 'unity-core', to: 'machine' },
    { id: 'j4', kind: 'jump', from: 'unity-core', to: 'world' },
    { id: 'j5', kind: 'jump', from: 'intention', to: 'insight' },
    { id: 'j6', kind: 'jump', from: 'model', to: 'unity-core' },
    { id: 'j7', kind: 'jump', from: 'impact', to: 'realisation' },
    { id: 'j8', kind: 'jump', from: 'mirror', to: 'creative-freedom' },
    { id: 'j9', kind: 'jump', from: 'resonance', to: 'transcendence' },
  ],
}
